name: Cross_Compile C++ on Push Test1
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Cross-Compiler
      run: sudo apt-get install gcc-arm-linux-gnueabihf  # Vervang dit door de juiste cross-compiler voor PYNQ

    - name: Create EXE_Bestanden Directory if not exists
      run: |
        if [ ! -d "EXE_Bestanden" ]; then
          mkdir EXE_Bestanden
        fi
      # Dit script controleert of de map bestaat en maakt deze aan als dat niet het geval is

    - name: Compile for PYNQ
      run: arm-linux-gnueabihf-gcc -o out.exe Test1.cpp # Compileer naar EXE_Bestanden-map
