name: Cross_Compile C++ on Push Test1
on:
  push:
    branches:
      - main  # Hier kun je de naam van de standaard branche aanpassen

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install g++
      run: sudo apt-get install g++
      
    - name: Install Cross-Compiler
      run: sudo apt-get install gcc-arm-linux-gnueabihf
 
    - name: Compile Test1.cpp
      run: arm-linux-gnueabihf-gcc -o my_program Test1.c

    
